# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inference_engine_pb2 as inference__engine__pb2


class InferenceServiceStub(object):
    """
    Represents the inference service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetResponse = channel.unary_unary(
                '/inference_engine.InferenceService/GetResponse',
                request_serializer=inference__engine__pb2.Request.SerializeToString,
                response_deserializer=inference__engine__pb2.Response.FromString,
                )


class InferenceServiceServicer(object):
    """
    Represents the inference service.
    """

    def GetResponse(self, request, context):
        """
        Gets a response when given a request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResponse,
                    request_deserializer=inference__engine__pb2.Request.FromString,
                    response_serializer=inference__engine__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference_engine.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """
    Represents the inference service.
    """

    @staticmethod
    def GetResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference_engine.InferenceService/GetResponse',
            inference__engine__pb2.Request.SerializeToString,
            inference__engine__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
