# Copyright © 2025 Seb Garrioch. All rights reserved.
# Published under the MIT License.

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "AI/ML Bootstrap (CI)"
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    name: "Build and Test .NET 9.0 API"
    runs-on: windows-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup .NET 9.0 SDK"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: "Restore Dependencies"
        working-directory: inference_api/
        run: dotnet restore

      - name: "Build"
        working-directory: inference_api/
        run: dotnet build --no-restore

      - name: "Test"
        working-directory: inference_api/
        run: dotnet test --no-build --verbosity normal
